recreate builder

diff --git a/images/develop/Dockerfile b/images/develop/Dockerfile
--- a/images/develop/Dockerfile
+++ b/images/develop/Dockerfile
@@ -1,54 +1,50 @@
+# Use a lightweight base image
 FROM ghcr.io/yuki-js/dotfiles/dotimage:latest
+
+# Set environment variables
+ENV PATH="/home/user/.asdf/bin:/home/user/.asdf/shims:$PATH"
+ENV user_ENV=development
+
+# Switch to root user for setup
 USER root
-RUN apt update -y && apt install postgresql libseccomp-dev rsync iproute2 screen -y --no-install-recommends \
-    && apt clean \
-    && rm -rf /var/lib/apt/lists/*
-
-RUN usermod -aG postgres user
-
-
-RUN mkdir -p /verdaccio/storage && \
-    chown -R user:user /verdaccio
-
 RUN echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user
 
+# Create application directory
+RUN mkdir /app && chown -R user:user /app
+
+# Switch to non-root user
 USER user
+WORKDIR /app
 
-WORKDIR /home/user/codes
+# Clone only necessary parts of the repository
+RUN git clone --depth 1 --filter=blob:none --sparse https://github.com/plasmicapp/plasmic.git plasmic \
+    && cd plasmic \
+    && git sparse-checkout set platform packages
 
-RUN git clone https://github.com/plasmicapp/plasmic.git plasmic --depth 1
+WORKDIR /app/plasmic
+RUN git submodule update --init --recursive --depth 1
+RUN rm /app/plasmic/.tool-versions
+RUN npm i -g yarn
+RUN yarn
 
-WORKDIR /home/user/codes/plasmic
+# Build specific components
+WORKDIR /app/plasmic/platform/wab
+RUN yarn install \
+    && yarn run build-css \
+    && make
 
-ENV PATH="/home/user/.asdf/bin:/home/user/.asdf/shims:$PATH"
-
+WORKDIR /app/plasmic/platform
 RUN <<EOF
-  cd /home/user/codes/plasmic
-  . "$HOME/.asdf/asdf.sh"
-  asdf install
-  npm install -g yarn verdaccio
-  yarn global add pm2
-EOF
-
-RUN <<EOF
-  yarn config set registry http://localhost:4873/
-  verdaccio --config /home/user/codes/plasmic/verdaccio-config.yaml &
-  sleep 5
-  
-  yarn install
-EOF
-
-WORKDIR /home/user/codes/plasmic/platform/wab
-RUN yarn install
-RUN yarn run build-css
-RUN make
-
-WORKDIR /home/user/codes/plasmic/platform
-RUN <<EOF
-  for i in "./canvas-packages/" "./host-test/" "./integration-tests/" "./live-frame/" "./loader-bundle-env/" "./loader-html-hydrate/" "./loader-tests/" "./react-renderer/" "./react-web-bundle/" "./sub/"; do
+  for i in "./canvas-packages/" "./live-frame/" "./loader-html-hydrate/" "./react-web-bundle/" "./sub/"; do
     cd $i
     yarn install
-    yarn run build
+    yarn run build || exit 1
     cd ..
   done
 EOF
+
+# Clean up unnecessary files to reduce image size
+RUN rm -rf /app/plasmic/platform/**/node_modules/.cache ~/.cache ~/.npm ~/.yarn ~/.yarnrc.yml ~/.yarnrc.yml.lock
+
+# Final user setup
+USER user
